package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/jiten-mobile/service/graph/model"
)

// Word is the resolver for the word field.
func (r *queryResolver) Word(ctx context.Context, word string) (*model.Word, error) {
	panic(fmt.Errorf("not implemented: Word - word"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
