// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Definition struct {
	ID           string   `json:"id"`
	Examples     []string `json:"examples,omitempty"`
	Meaning      *string  `json:"meaning,omitempty"`
	PartOfSpeech *string  `json:"partOfSpeech,omitempty"`
}

type Query struct {
}

type Word struct {
	ID            string   `json:"id"`
	Word          string   `json:"word"`
	Synonyms      []string `json:"synonyms,omitempty"`
	Antonyms      []string `json:"antonyms,omitempty"`
	RelatedTerms  []string `json:"relatedTerms,omitempty"`
	Pronunciation *string  `json:"pronunciation,omitempty"`
	Tense         *string  `json:"tense,omitempty"`
}
